name: proj1
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7  
  auto_size_text: ^3.0.0
  concentric_transition: ^1.0.3
  cupertino_icons: ^1.0.5
  flutter_sms: ^2.3.3
  flutter_svg: ^1.1.0
  built_collection: ^5.1.1
  built_value: ^8.4.0
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.2.1
  cloud_firestore_platform_interface: ^5.5.10
  cloud_firestore_web: ^2.6.19
  file_picker: ^4.5.1
  firebase_auth: ^3.4.1
  firebase_auth_platform_interface: ^6.3.1
  firebase_auth_web: ^3.3.19
  firebase_core: ^1.19.1
  fluttertoast: ^8.1.1
  firebase_core_platform_interface: ^4.4.3
  firebase_core_web: ^1.6.6
  firebase_storage: ^10.3.1
  firebase_storage_platform_interface: ^4.1.10
  firebase_storage_web: ^3.2.19
  flutter_animate: ^1.0.0
  font_awesome_flutter: ^10.1.0
  from_css_color: ^2.0.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.0
  google_sign_in_android: ^6.0.1
  google_sign_in_ios: ^5.4.0
  google_sign_in_platform_interface: ^2.2.0
  google_sign_in_web: ^0.10.2
  http: ^0.13.5
  image_picker: 
  intl: ^0.17.0
  json_path: ^0.4.1
  json_serializable: ^6.3.1
  lottie: ^1.2.1
  mime_type: ^1.0.0
  page_transition: ^2.0.4
  plugin_platform_interface: ^2.1.2
  rxdart: ^0.27.4
  responsive_builder: ^0.4.3
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.1.0
  sign_in_with_apple_platform_interface: ^1.0.0
  sign_in_with_apple_web: ^1.0.1
  timeago: ^3.2.2
  url_launcher: ^6.1.5
  provider: ^6.0.4
  permission_handler: ^10.2.0


dev_dependencies:
  build_runner: ^2.2.0
  built_value_generator: ^8.4.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
 

